name: Update Deployment YAML

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the deployment repository
      - name: Checkout deployment repo
        uses: actions/checkout@v3
        with:
          repository: jtb75/weather-wizard-deployment
          token: ${{ secrets.GH_PAT }}

      # Step 2: Update the weather-front-end.yaml file
      - name: Update deployment YAML
        run: |
          cd deploy/k8s
          sed -i "s|image: harbor.k8s.ng20.org/weather-wizard/weather-front-end:.*|image: harbor.k8s.ng20.org/weather-wizard/weather-front-end:${{ github.event.workflow_run.outputs.new_version }}|" weather-front-end.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update weather-front-end image to version ${{ github.event.workflow_run.outputs.new_version }}"
          git push
